runs=10

files_results=(frnq__ex3 frnq_1.1ex3 frnq_1.nex3);
strs=(./nq.posl ./nq_1.1.posl ./nq_1.n.posl);

n=1500
cores=6


for item in ${files_results[*]}
do
	echo "---- $n queens : $cores  -----" >> $item
done

for (( j = 0; j < 3; j++ ))
do			
	for (( i = 0; i < $runs; i++ ))
	do
		mpiexec.mpich -np $cores ./POSL/bin_par/POSL nqueens $n ${strs[j]} >> ${files_results[j]}				
	done
	echo "----END-----" >> ${files_results[j]}
	#w >> ${files_results[j]}
	echo "   " >> ${files_results[j]}
done

