runs=35

files_results=(frnq_1.1 frnq_1.n);
strs=(./nq_1.1.posl ./nq_1.n.posl);

n=1000
cores=40


for item in ${files_results[*]}
do
	echo "---- $n queens : $cores  -----" >> $item
done

for (( j = 0; j < 2; j++ ))
do			
	for (( i = 0; i < $runs; i++ ))
	do
		mpiexec.mpich2 -np $cores ./bin/POSL nqueens $n ${strs[j]} >> ${files_results[j]}				
	done
	echo "----END-----" >> ${files_results[j]}
	#w >> ${files_results[j]}
	echo "   " >> ${files_results[j]}
done

